image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - build

before_script:
  - &before_script |
    set -x
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy
    nix profile install .#cachix
    export USER=root
    cachix use jrobsonchase
    pkill nix-daemon
    TMP=$NIX_REMOTE
    unset NIX_REMOTE
    nix-daemon &
    export NIX_REMOTE=$TMP
    set +x

flake_update:
  rules:
    - if: '$FLAKE_UPDATE == 1 && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  script:
    - nix flake update

check:
  stage: build
  script:
    - nix flake check
  rules:
    - if: '$FLAKE_UPDATE != 1'

build_nixos:
  extends: check
  before_script:
    - *before_script
    - nix profile install .#nixos-rebuild
  script:
    - cachix watch-exec jrobsonchase nixos-rebuild -- build --flake .#tarvos -L --max-jobs 8

build_home:
  extends: check
  script:
    - cachix watch-exec jrobsonchase nix -- build .#homeConfigurations."josh@tarvos".activationPackage -L --max-jobs 8