image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - build

before_script:
  - &before_script |
    set -x
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy
    nix profile install .#cachix
    export USER=root
    cachix use jrobsonchase
    pkill nix-daemon
    TMP=$NIX_REMOTE
    unset NIX_REMOTE
    nix-daemon &
    export NIX_REMOTE=$TMP
    set +x

flake_update:
  stage: build
  rules:
    - if: '$FLAKE_UPDATE == "1" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - *before_script
    - mkdir -p /root/.ssh
    - cat "$flake_deploy_key" > /root/.ssh/id_rsa
    - git config user.email josh@robsonchase.com
    - git config user.name "Josh Robson Chase"
    - git remote set-url origin ssh://git@gitlab.com/jrobsonchase/nixos-config
  script:
    - git fetch origin
    - git checkout flake-update
    - git merge main
    - nix flake update --override-input private ./private-dummy
    - 'git commit -am "auto: Update flake inputs"'
    - git push

check:
  stage: build
  script:
    - nix flake check
  rules:
    - if: '$FLAKE_UPDATE != "1"'

build_nixos:
  extends: check
  before_script:
    - *before_script
    - nix profile install .#nixos-rebuild
  script:
    - cachix watch-exec jrobsonchase nixos-rebuild -- build --flake .#tarvos -L --max-jobs 8

build_home:
  extends: check
  script:
    - cachix watch-exec jrobsonchase nix -- build .#homeConfigurations."josh@tarvos".activationPackage -L --max-jobs 8