image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - build

before_script:
  - &before_script |
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy

check:
  stage: build
  script:
    - nix flake check

build_nixos:
  stage: build
  script:
    - nix run .#nixos-rebuild -- build --flake .#tarvos

build_home:
  stage: build
  script:
    - nix run .#home-manager -- build --flake .#josh@tarvos