image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - update
  - build
  - push

before_script:
  - &before_script |
    set -x
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy
    nix profile install .#cachix
    export USER=root
    cachix use jrobsonchase
    pkill nix-daemon
    TMP=$NIX_REMOTE
    unset NIX_REMOTE
    nix-daemon &
    export NIX_REMOTE=$TMP
    set +x

.ignored:
  - &extra_git_setup |
    set -x
    mkdir -p /root/.ssh
    cat "$flake_deploy_key" > /root/.ssh/id_rsa
    chmod 0600 /root/.ssh/id_rsa
    echo "$GITLAB_KNOWN_HOST" >> /root/.ssh/known_hosts
    git config user.email josh@robsonchase.com
    git config user.name "Josh Robson Chase"
    git reset --hard
    git remote set-url origin ssh://git@gitlab.com/jrobsonchase/nixos-config
    git fetch origin
    set +x

flake_update:
  stage: update
  rules:
    - if: '$FLAKE_UPDATE == "1" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - *before_script
    - *extra_git_setup
  script:
    # NB: These checkout/merge shenanigans are to ensure that main is always the
    # first parent.
    - git checkout main
    - git merge origin/flake-update --no-edit
    - git checkout flake-update
    - git merge origin/main --ff-only
    - nix flake update --override-input private ./private-dummy
    - 'git commit -am "auto: Update flake inputs"'
    - git push

check:
  stage: build
  script:
    - nix flake check
  rules:
    - if: '$FLAKE_UPDATE != "1"'

build_nixos:
  extends: check
  before_script:
    - *before_script
    - nix profile install .#nixos-rebuild
  script:
    - cachix watch-exec jrobsonchase nixos-rebuild -- build --flake .#tarvos -L --max-jobs 8

build_home:
  extends: check
  script:
    - cachix watch-exec jrobsonchase nix -- build .#homeConfigurations."josh@tarvos".activationPackage -L --max-jobs 8

push_master:
  stage: push
  before_script:
    - *before_script
    - *extra_git_setup
  script:
    - git push origin HEAD:main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "flake-update"'