image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - update
  - build
  - push


.ignored:
  - &before_script |
    set -x
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy
    set +x

  - &cachix_setup |
    set -x
    nix profile install .#cachix
    export USER=root
    cachix use jrobsonchase
    cachix use nix-on-droid
    pkill nix-daemon
    TMP=$NIX_REMOTE
    unset NIX_REMOTE
    nix-daemon &
    export NIX_REMOTE=$TMP
    set +x

  - &extra_git_setup |
    set -x
    mkdir -p /root/.ssh
    cat "$flake_deploy_key" > /root/.ssh/id_rsa
    chmod 0600 /root/.ssh/id_rsa
    echo "$GITLAB_KNOWN_HOST" >> /root/.ssh/known_hosts
    git config user.email "$GITLAB_USER_EMAIL"
    git config user.name "$GITLAB_USER_NAME"
    git reset --hard
    git remote set-url origin ssh://git@gitlab.com/jrobsonchase/nixos-config
    git fetch origin
    set +x

flake_update:
  stage: update
  rules:
    - if: '$FLAKE_UPDATE == "1" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - *before_script
    - *extra_git_setup
  script:
    - git checkout main
    - nix flake update --override-input private ./private-dummy
    - 'git commit -am "auto: Update flake inputs"'
    - 'git push --force origin HEAD:flake-update'

check:
  stage: build
  before_script:
    - *before_script
    - *cachix_setup
  script:
    - nix flake check
  rules:
    - if: '$FLAKE_UPDATE != "1"'

build_nixos:
  extends: check
  before_script:
    - *before_script
    - *cachix_setup
    - nix profile install .#nixos-rebuild
  script:
    - cachix watch-exec jrobsonchase nixos-rebuild -- build --flake .#tarvos -L --max-jobs 8

build_home:
  extends: check
  script:
    - cachix watch-exec jrobsonchase nix -- build .#homeConfigurations."josh@tarvos".activationPackage -L --max-jobs 8

build_droid:
  extends: check
  script:
    - cachix watch-exec jrobsonchase nix -- build .#nixOnDroidConfigurations.device.activationPackage -L --max-jobs 8 --impure

push_main:
  stage: push
  before_script:
    - *before_script
    - *extra_git_setup
  script:
    - git push origin HEAD:main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "flake-update"'