image: nixpkgs/nix-flakes:latest

stages:
  - trigger
  - external
  - wait-external
  - update
  - push

.ignored:
  - &before_script |
    nix profile install nixpkgs#nixVersions.nix_2_19 nixpkgs#git nixpkgs#openssh
    nix registry add private gitlab:jrobsonchase/nixos-config?dir=private-dummy
    mkdir -p /root/.ssh
    cat "$flake_deploy_key" > /root/.ssh/id_rsa
    chmod 0600 /root/.ssh/id_rsa
    echo "$GITLAB_KNOWN_HOST" >> /root/.ssh/known_hosts
    echo "$GITHUB_KNOWN_HOST" >> /root/.ssh/known_hosts
    git config user.email "$GITLAB_USER_EMAIL"
    git config user.name "$GITLAB_USER_NAME"
    git reset --hard
    git remote set-url origin ssh://git@gitlab.com/jrobsonchase/nixos-config
    git fetch origin $CI_COMMIT_REF_NAME
    set -o pipefail

flake_update:
  stage: update
  rules:
    - if: '$FLAKE_UPDATE == "1" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  before_script:
    - *before_script
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - nix flake update --commit-lock-file
    - 'git push --force origin HEAD:flake-update'

push_built:
  stage: push
  before_script:
    - *before_script
  script:
    - git push -o ci.skip origin HEAD:built
  rules:
    - if: '$CI_COMMIT_REF_NAME != "built" && $FLAKE_UPDATE != "1"'

push_main:
  stage: push
  before_script:
    - *before_script
  script:
    - git push -o ci.skip origin HEAD:main
  rules:
    - if: '$CI_COMMIT_REF_NAME == "flake-update"'

hydra-trigger:
  stage: trigger
  rules:
    - if: '$FLAKE_UPDATE != "1"'
  script:
    - nix profile install nixpkgs#nixVersions.nix_2_19
    - ./.hydra/trigger_hydra.sh https://hydra.robsonchase.com nixos-config $CI_COMMIT_REF_NAME

hydra-wait:
  stage: wait-external
  timeout: 30m
  rules:
    - if: '$FLAKE_UPDATE != "1"'
  script:
    - nix profile install nixpkgs#nixVersions.nix_2_19
    - ./.hydra/await_jobset.sh https://hydra.robsonchase.com nixos-config $CI_COMMIT_REF_NAME $CI_COMMIT_SHA