image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - build

before_script:
  - &before_script |
    set -x
    nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
    nix profile install nixpkgs#git
    nix flake lock --override-input private ./private-dummy
    nix profile install .#cachix
    cachix use jrobsonchase
    set +x

check:
  stage: build
  script:
    - nix flake check

build_nixos:
  stage: build
  before_script:
    - *before_script
    - nix profile install .#nixos-rebuild
  script:
    - cachix watch-exec jrobsonchase nixos-rebuild -- build --flake .#tarvos

build_home:
  stage: build
  before_script:
    - *before_script
    - nix profile install .#home-manager
  script:
    - cachix watch-exec jrobsonchase home-manager -- build --flake .#josh@tarvos