image: registry.gitlab.com/jrobsonchase/nix-bootstrap

stages:
  - check
  - build

before_script:
  - nix registry add nixpkgs github:nixos/nixpkgs/nixos-unstable
  - nix profile install nixpkgs#git
  - nix flake lock --override-input private ./private-dummy

check:
  stage: check
  script:
    - nix flake check

build_nixos:
  stage: build
  script:
    - nix run nixpkgs#nixos-rebuild -- build .#tarvos --flake

